### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by earnaud** [meetU-MasterStudents/2018---2019-Equipe-11#1]
| Score | Assigned | Implemented |
| --- | --- | --- |
| C alpha | :white_check_mark: | :white_check_mark: |
| All atoms | :white_check_mark: | :white_check_mark: |
| Coarse Grain | :white_check_mark: | :white_check_mark: |

**Comment by earnaud** [comment]
On est bon pour cette issue?

**Comment by althonos** [comment]
Yes !
